### ISSUE TITLE
Serialization of negative int value

### ISSUE THREAD

**Issue by chrisCesar34** [arangodb/java-velocypack#5]
When serializing an object having negative int value for one of its instance field, the returned serialized object have a weird value instead of the negative int value.

For example, if I call the following piece of code with an object having -50 as value for one of its int field, the serialized value for this field is 4294967246;

VPack vpack = vpack();
System.out.println(vpack.serialize(object).toString());

**Comment by mpv1989** [comment]
I added some tests which shows that this work with the current version. Which version do you use?

**Comment by mvollmary** [comment]
@chrisCesar34 There was a bug in vpack-json parsing which I fixed a couple of weeks ago (see [here](https://github.com/arangodb/java-velocypack/commit/bee3815a620c33a81917729db083f85ee20c3706)). You can try it out by using version `1.0.12-SNAPSHOT`. I will release a new version within this month

**Comment by chrisCesar34** [comment]
@mpv1989 we use velocypack 1.0.11 with with arangodb-java-driver 4.2.4. We will test the snapshot a give you the result. Thanks.

**Comment by gontard** [comment]
@mpv1989 i works with @chrisCesar34 . The problem remains unresolved with the SNAPSHOT version.

I described how to reproduce it in this related issue: https://github.com/arangodb/arangodb-java-driver/issues/151

**Comment by mvollmary** [comment]
@chrisCesar34 @gontard Sry for the late response.
I added some tests. It seems like the problem only occurs when serializing an negative `int` and deserializing it as `long`. I am on it.

**Comment by mvollmary** [comment]
@chrisCesar34 @gontard I pushed a fix. Tests are green, if it works for you I will release a new version.

**Comment by gontard** [comment]
Hello @mvp,

thanks for your help. I tried the latest `1.0.12-SNAPSHOT` and unfortunately the fix does not correct our issue.
Could you try to reproduce my problem using [the test i have attached](https://github.com/arangodb/arangodb-java-driver/issues/151#issuecomment-334709021) to this related issue https://github.com/arangodb/arangodb-java-driver/issues/151 ?

**Comment by mvollmary** [comment]
@gontard @chrisCesar34 Thanks for the response. I reproduced the problem with your test (thanks for that). I was able to fix the problem. I will write some more tests and see whether I find a better solution then the current one.

I already deployed the current snapshot. Feel free to test.

**Comment by gontard** [comment]
@mpv1989 I just finish to test with the last SNAPSHOT and it works !
Thanks a lot for your help.

When can we expect a new release with this fix ?

**Comment by mvollmary** [comment]
@gontard I will add some more tests and then release a new version of this project and the driver today.

**Comment by gontard** [comment]
@mpv1989 thanks again.
